schema_version: 1

context:
  name: mixpanel
  version: "5.3.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/mixpanel-${{ version }}.tar.gz
  sha256: f08baa1ddb9357a833ceae168c25f82718e011c6b883d0898d080d141a26b793

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=61.0
  run:
    - python >=${{ python_min }}
    - requests >=2.4.2,<3
    - httpx >=0.27.0
    - pydantic >=2.0.0,<2.12
    - asgiref >=3.0.0
    - json-logic ==0.7.0a0

tests:
  - python:
      imports:
        - mixpanel
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Official Mixpanel library for Python
  license: Apache-2.0
  license_file: LICENSE.txt
  homepage: https://github.com/mixpanel/mixpanel-python

extra:
  recipe-maintainers:
    - rabah-khalek
    - synapticarbors
